name: example-workflow
on:
  pull_request_review_comment:
    types: [created]
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'dbt build'}}
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo 1
