name: example-workflow
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.event.comment.body == 'dbt build'}}
    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo 1
