name: example-workflow
on:
  issue_comment:
    types:
      - created
permissions:
  contents: read
  issues: read
  pull-requests: read
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'dbt build'}}
    steps:
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - uses: actions/checkout@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
        
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo 1
