name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'portfolio/configs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo 1
