name: build-push

on:
  workflow_dispatch:
    inputs:
      sha:
        type: string
        description: Write commit' sha
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Printing
        run: |
          if [ ${{ github.event.inputs.sha }} = "" ]; then
            sha=${{ github.sha }}
          else
            sha=${{ github.event.inputs.sha }}
          fi
          
          echo "${{ github.event.inputs.sha }}"
          response=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}12" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/jaklau/portfolio/commits/${{ github.sha }} --fail)
          
