name: build-push

on:
  workflow_dispatch:
  push:
    paths:
      - 'configs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step following 'Import Secrets'
        run: |
          echo "PASS=sveiki" >> $GITHUB_ENV
      - name: Step following 'Import Secrets2'
        run: |
          env
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script # run main.py
        run: python debezium.py 0 "${{ steps.abc.outputs.modified }}"
