name: build-push

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Printing
        run: |
          echo "PR_NUMBER=${{ github.event.number }}"
          echo "PR_TITLE=${{ github.event.pull_request.title }}"
          echo "PR_BODY=${{ github.event.pull_request.body }}"
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}"
          echo "PR_CREATED_AT=${{ github.event.pull_request.created_at }}"
          echo "PR_UPDATED_AT=${{ github.event.pull_request.updated_at }}"
          echo "PR_URL=${{ github.event.pull_request.html_url }}"
