name: build-push

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'configs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step following 'Import Secrets'
        run: |
          echo "PASS=sveiki" >> $GITHUB_ENV
      - name: Step following 'Import Secrets2'
        run: |
          env
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39.2.2
        with:
          files: configs/*.json  # Alternatively using: `docs/**` or `docs`

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: List all deleted files
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            echo "$file was changed"
          done
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: send configs
        run: python debezium.py "add" "${{ steps.abc.outputs.added }}"

      - name: update configs
        run: python debezium.py "update" "${{ steps.abc.outputs.modified }}"
