name: build-push

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Printing
        run: |
          echo ${{ github.workspace }}.${{ github.sha }}
