name: python-lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    # branches-ignore:
    #   - master
    #   - main
    paths:
      - '**.py'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.py'

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff linter
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: ruff check --config .github/workflows/ruff.toml --preview ${{ steps.changed-files.outputs.all_changed_files }}         
