name: python-lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    # branches-ignore:
    #   - master
    #   - main
    paths:
      - '**.py'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.py'

      - name: Run sqlfluff linter
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: | 
          ruff lint for file in "${{ steps.changed-files.outputs.all_changed_files }}"; do
            "$file"
          done


      - name: Run ruff linter new
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        uses: chartboost/ruff-action@v1
        with:
          src: ${{ steps.changed-files.outputs.all_changed_files }} 
          args: --config .github/workflows/ruff.toml --preview

  python-lint2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.py'

      - name: Run ruff linter new
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        uses: chartboost/ruff-action@v1
        with:
          src: ${{ steps.changed-files.outputs.all_changed_files }}
          args: --config .github/workflows/ruff.toml --preview
